[project]
name = 'Primordial-Chaos-Harnessing-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.existential-risk-containment]
path = 'contracts/existential-risk-containment.clar'
clarity_version = 2
epoch = 2.5

[contracts.fundamental-force-balancing]
path = 'contracts/fundamental-force-balancing.clar'
clarity_version = 2
epoch = 2.5

[contracts.potential-energy-tapping]
path = 'contracts/potential-energy-tapping.clar'
clarity_version = 2
epoch = 2.5

[contracts.reality-seed-germination]
path = 'contracts/reality-seed-germination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
